import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
//import { extractRouterConfig } from "uploadthing/server";
//import { ourFileRouter } from "./api/uploadthing/core";
//import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
//import { Toaster } from "sonner";
import AuthProvider from "@/components/AuthProvider";
import { inter } from "./fonts";
import SideNav from "@/components/SideNav";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Gamerzone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            {/* <NextSSRPlugin
              /**
               * The `extractRouterConfig` will extract **only** the route configs
               * from the router to prevent additional information from being
               * leaked to the client. The data passed to the client is the same
               * as if you were to fetch `/api/uploadthing` directly.
               * /
              routerConfig={extractRouterConfig(ourFileRouter)}
            />*/}
            <div className="flex h-screen relative flex-col md:flex-row md:overflow-hidden">
        <SideNav />
        <Header/>
      <div className="w-full md:overflow-y-auto">
        {children}
      </div>
    </div>
            {/*<Toaster richColors />*/}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
