import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import AuthProvider from "@/components/AuthProvider";
import { inter } from "./fonts";
import SideNav from "@/components/SideNav";
import Header from "@/components/Header";
import { UserProvider } from "@/context/UserContext";
import { SessionProvider } from "next-auth/react";


export const metadata: Metadata = {
  title: "Gamerzone",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <SessionProvider>
              <UserProvider>
                <div className="flex h-screen relative flex-col md:flex-row md:overflow-hidden">
                  <SideNav />
                  <div className="flex-1 flex flex-col md:overflow-y-auto">
                    <Header />
                    <main className="flex-1 overflow-y-auto">{children}</main>
                  </div>
                </div>
              </UserProvider>
            </SessionProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
